# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: explory
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyqt5-tools
        python -m pip install pyinstaller
        python -m pip install pylint
        python -m pip install mypy

    - name: Lint with pylint
      run: pylint explory/explory.py --exit-zero

    - name: mypy
      run: mypy explory/explory.py

    - name: unittests
      run: python -m unittest explory.tests.tests

    - name: make exe
      run: pyinstaller --onefile ---debug=all --console explory/explory.py

    - name: Artifact upload
      uses: actions/upload-artifact@v2
      with:
        name: explory
        path: dist/
